title: Natacha Chenevoy
description: Data Science Postgraduate student in Criminology
show_downloads: false
theme: jekyll-theme-cayman

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar

defaults:
  -
    scope:
      path: ''
    values:
      layout: 'default'
  -
    scope:
          path: "_posts/"
      values: 'default'
      
gems:
  - jekyll-mentions

plugins:
  - jekyll-seo-tag
